name: Build Chroma for 1.40.8

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
      - name: Run build script
        shell: pwsh
        run: |
          .\build.ps1
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Chroma-built
          path: output/Chroma.dll
